name = input("Input your name: ")
age = input("Enter your age: ")
print("Your name is:", name, ", your age is", age, "years old")
print("Your name is {}, and your age is {} years old".format(name, age))
print(f"Your name is {name}, and yoru age is {age}")